### ISSUE TITLE
Update admin user add/edit pages to handle different user types

### ISSUE THREAD

**Issue by bot190** [chopshop-166/SignInWebApp#36]
The admin new user and edit user pages use a separate form and logic from the registration page so they need to be updated as well. Ideally we would use the same form object(s) to reduce the duplicate code.

**Comment by msoucy** [comment]
@JoeJanickiChSh would you like to take a look at this?

**Comment by msoucy** [comment]
Instead of putting everything in one form, it probably makes sense to have a "role data" column in the user lists, with buttons for the data specific to the role that the user has.

We can probably cheat like we do now and say there's a limit of two guardians, and manually convert to the DB format.

For the guardian data, maybe a set of drop down fields where one can select students?

There's some code [here](https://stackoverflow.com/questions/30668029/creating-a-form-with-a-varying-number-of-repeated-subform-in-flask-wtforms) that we can probably leverage to make the guardian form look nicer/be more dynamic

**Comment by msoucy** [comment]
Addressed in #56 for student data

**Comment by msoucy** [comment]
Fixed via #75
